# Generated by Django 3.2.12 on 2022-09-12 06:18

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examname', models.CharField(blank=True, max_length=100)),
                ('facultyname', models.CharField(blank=True, max_length=50)),
                ('totalmarks', models.IntegerField(blank=True)),
                ('starttime', models.DateTimeField(default=datetime.datetime(2022, 9, 12, 11, 48, 7, 216618))),
                ('endtime', models.DateTimeField(default=datetime.datetime(2022, 9, 12, 11, 48, 7, 216651))),
                ('examdept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faculty.departmentinfo')),
            ],
            options={
                'verbose_name_plural': 'Exam Info',
            },
        ),
        migrations.CreateModel(
            name='SubjectInfo',
            fields=[
                ('subjectname', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('subjectcode', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Subject Info',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(blank=True, max_length=50)),
                ('question', models.TextField(blank=True, max_length=1000)),
                ('option1', models.CharField(blank=True, max_length=500, null=True)),
                ('option2', models.CharField(blank=True, max_length=500, null=True)),
                ('option3', models.CharField(blank=True, max_length=500, null=True)),
                ('option4', models.CharField(blank=True, max_length=500, null=True)),
                ('answer', models.CharField(blank=True, max_length=500)),
                ('marks', models.IntegerField(blank=True)),
                ('examname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.examinfo')),
            ],
            options={
                'verbose_name_plural': 'Questions',
            },
        ),
        migrations.AddField(
            model_name='examinfo',
            name='examsubj',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.subjectinfo'),
        ),
    ]
