# Generated by Django 5.2 on 2025-04-14 21:36

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(blank=True)),
                ('student', models.CharField(blank=True, max_length=100)),
                ('examname', models.CharField(blank=True, max_length=100)),
                ('deptname', models.CharField(blank=True, max_length=50)),
                ('subjname', models.CharField(blank=True, max_length=50)),
                ('totalmarks', models.IntegerField(blank=True)),
                ('marksgain', models.IntegerField(blank=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Result',
            },
        ),
        migrations.CreateModel(
            name='SubjectInfo',
            fields=[
                ('subjectname', models.CharField(blank=True, max_length=100, primary_key=True, serialize=False)),
                ('subjectcode', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name_plural': 'Subject Info',
            },
        ),
        migrations.CreateModel(
            name='ExamInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examname', models.CharField(blank=True, max_length=100)),
                ('facultyname', models.CharField(blank=True, max_length=50)),
                ('totalmarks', models.IntegerField(blank=True)),
                ('starttime', models.DateTimeField(default=datetime.datetime(2025, 4, 15, 3, 6, 39, 504739))),
                ('endtime', models.DateTimeField(default=datetime.datetime(2025, 4, 15, 3, 6, 39, 504787))),
                ('examdept', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faculty.departmentinfo')),
                ('examsubj', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.subjectinfo')),
            ],
            options={
                'verbose_name_plural': 'Exam Info',
            },
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(blank=True, max_length=50)),
                ('question', models.TextField(blank=True, max_length=1000)),
                ('option1', models.CharField(blank=True, max_length=500, null=True)),
                ('option2', models.CharField(blank=True, max_length=500, null=True)),
                ('option3', models.CharField(blank=True, max_length=500, null=True)),
                ('option4', models.CharField(blank=True, max_length=500, null=True)),
                ('answer', models.CharField(blank=True, max_length=500)),
                ('marks', models.IntegerField(blank=True)),
                ('examname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.examinfo')),
            ],
            options={
                'verbose_name_plural': 'Questions',
            },
        ),
    ]
