# Generated by Django 3.2.12 on 2022-09-12 06:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20220912_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinfo',
            name='endtime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 12, 12, 12, 27, 19744)),
        ),
        migrations.AlterField(
            model_name='examinfo',
            name='starttime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 12, 12, 12, 27, 19717)),
        ),
    ]
