# Generated by Django 3.2.12 on 2022-09-12 07:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20220912_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinfo',
            name='endtime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 12, 13, 14, 55, 582669)),
        ),
        migrations.AlterField(
            model_name='examinfo',
            name='starttime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 12, 13, 14, 55, 582642)),
        ),
    ]
