# Generated by Django 3.2.12 on 2022-09-13 05:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20220912_2348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(blank=True)),
                ('student', models.CharField(blank=True, max_length=100)),
                ('examname', models.CharField(blank=True, max_length=100)),
                ('deptname', models.CharField(blank=True, max_length=50)),
                ('subjname', models.CharField(blank=True, max_length=50)),
                ('totalmarks', models.IntegerField(blank=True)),
                ('marksgain', models.IntegerField(blank=True)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name_plural': 'Result',
            },
        ),
        migrations.AlterField(
            model_name='examinfo',
            name='endtime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 10, 47, 57, 549594)),
        ),
        migrations.AlterField(
            model_name='examinfo',
            name='starttime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 13, 10, 47, 57, 549562)),
        ),
    ]
