# Generated by Django 3.2.12 on 2022-09-13 19:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_auto_20220913_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinfo',
            name='endtime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 14, 1, 2, 51, 763693)),
        ),
        migrations.AlterField(
            model_name='examinfo',
            name='starttime',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 14, 1, 2, 51, 763665)),
        ),
    ]
