# Generated by Django 3.2.12 on 2022-09-12 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentInfo',
            fields=[
                ('depname', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('dephead', models.CharField(blank=True, max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Department Info',
            },
        ),
        migrations.CreateModel(
            name='FacultyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('number', models.CharField(blank=True, max_length=12)),
                ('department', models.CharField(blank=True, max_length=12)),
                ('subject', models.CharField(blank=True, max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Faculty Info',
            },
        ),
    ]
