# Generated by Django 5.2 on 2025-04-14 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('number', models.CharField(blank=True, max_length=12)),
                ('department', models.CharField(blank=True, max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Student Info',
            },
        ),
        migrations.CreateModel(
            name='ExamResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.IntegerField(blank=True, null=True)),
                ('studname', models.CharField(blank=True, max_length=50, null=True)),
                ('deptname', models.CharField(blank=True, max_length=50, null=True)),
                ('subjname', models.CharField(blank=True, max_length=50, null=True)),
                ('examname', models.CharField(blank=True, max_length=100, null=True)),
                ('question', models.CharField(blank=True, max_length=500, null=True)),
                ('answer', models.CharField(blank=True, max_length=1000, null=True)),
                ('totalmarks', models.IntegerField(blank=True, null=True)),
                ('marksgain', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.studentinfo')),
            ],
            options={
                'verbose_name_plural': 'Exam Response',
            },
        ),
        migrations.CreateModel(
            name='StuExamHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examname', models.CharField(blank=True, max_length=100)),
                ('appeareddate', models.DateTimeField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=50)),
                ('totalmarks', models.IntegerField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentinfo')),
            ],
            options={
                'verbose_name_plural': 'Student Exam History',
            },
        ),
    ]
