# Generated by Django 3.2.12 on 2022-09-12 06:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
                ('address', models.CharField(blank=True, max_length=50)),
                ('number', models.CharField(blank=True, max_length=12)),
                ('department', models.CharField(blank=True, max_length=12)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Student Info',
            },
        ),
        migrations.CreateModel(
            name='ExamResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studname', models.CharField(blank=True, max_length=50, null=True)),
                ('deptname', models.CharField(blank=True, max_length=50, null=True)),
                ('subjname', models.CharField(blank=True, max_length=50, null=True)),
                ('examname', models.CharField(blank=True, max_length=100, null=True)),
                ('question', models.CharField(blank=True, max_length=500, null=True)),
                ('answer', models.CharField(blank=True, max_length=1000, null=True)),
                ('totalmarks', models.IntegerField(blank=True)),
                ('marksgain', models.IntegerField(blank=True, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.studentinfo')),
            ],
            options={
                'verbose_name_plural': 'Exam Response',
            },
        ),
    ]
