# Generated by Django 3.2.12 on 2022-09-12 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examresponse',
            old_name='student',
            new_name='studept',
        ),
    ]
