# Generated by Django 3.2.12 on 2022-09-12 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_student_examresponse_studept'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examresponse',
            old_name='studept',
            new_name='student',
        ),
    ]
