# Generated by Django 3.2.12 on 2022-09-12 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_rename_studept_examresponse_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresponse',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
