# Generated by Django 3.2.12 on 2022-09-13 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_examresponse_totalmarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='StuExamHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examname', models.CharField(blank=True, max_length=100)),
                ('appeareddate', models.DateTimeField(blank=True, null=True)),
                ('subject', models.CharField(blank=True, max_length=50)),
                ('totalmarks', models.IntegerField(blank=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentinfo')),
            ],
            options={
                'verbose_name_plural': 'Student Exam History',
            },
        ),
    ]
